version: '3.4'
services:
  rasa:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    - ./models:/app/models
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\""
    ports:
    - '5005:5005'
    networks:
    - all

  rasa-actions:
    image: rasa-bot:latest
    working_dir: /app
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    command: ["rasa","run","actions"]
    ports:
    - '5005:5005'
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.networks.enable_ipv6:"true"
